repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  -   id: trailing-whitespace
  -   id: end-of-file-fixer
  -   id: check-yaml

- repo: https://github.com/sqlfluff/sqlfluff
  rev: 3.0.7
  hooks:
    - id: sqlfluff-lint
      args: [--dialect, mysql]
    - id: sqlfluff-fix
      args: [--dialect, mysql]

- repo: https://github.com/TekWizely/pre-commit-golang
  rev: v1.0.0-rc.1
  hooks:
    - id: go-fmt
    - id: go-vet-mod
    - id: go-staticcheck-mod
    - id: my-cmd-mod
      name: go-generate-mod
      args: [go, generate, ./...]

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.56.0'
    hooks:
    -   id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
